from snakemake.utils import min_version

#### set minimum snakemake version ####
min_version("8.27")

#### load config ####
configfile: "config/config.yaml"

#### load rules ####
include: "rules/common.smk"
include: "rules/create_fastq.smk"
include: "rules/move_fastq.smk"

#### target rules ####
rule all:
    input: 
        get_final_output(),
